# Generated by Django 2.1 on 2018-11-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20181105_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
