# Generated by Django 2.1 on 2018-11-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20181105_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='status',
        ),
    ]
