# Generated by Django 2.1 on 2018-11-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20181105_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
