# Generated by Django 2.1 on 2018-11-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
