# Generated by Django 2.1 on 2018-11-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20181105_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
